import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../src/styles/home.module.css'
import menu from '../src/scripts/menu.mjs'
import Link from 'next/link'

const legend = {
  "01": "one",
  "02": "two",
  "03": "three",
  "04": "four",
}

function Home( {posts} ) {

  posts = posts[0]

  const urlValidate = (url: any) => {
    
    let flag = 0
    Object.keys(posts.topics).map(key => {
      if (key == url) {
        flag = 1
      }
    })
    if (flag == 1) return 1
    else return 0
  }

  const [post, Setpost] = React.useState({
    title: `${posts.topics.one}`,
    image: `${posts.images.one}`,
    content: `${posts.content.one}`,
    current: `one`,
    link: `./${posts.topics.one}`,
    path: `./[id]`
  })

  const Handlechange = (e: any) => {
    if (urlValidate(legend[e.target.innerHTML]) == 1) {
      Setpost({
        title: `${posts.topics[legend[e.target.innerHTML]]}`,
        image: `${posts.images[legend[e.target.innerHTML]]}`,
        content: `${posts.content[legend[e.target.innerHTML]]}`,
        current: `${legend[e.target.innerHTML]}`,
        link: `./${posts.topics[legend[e.target.innerHTML]]}`,
        path: `./[id]`
      })
    }
    else {
      Setpost({
        title: ` `,
        image: `/placeholder.png`,
        content: ` `,
        current: `${legend[e.target.innerHTML]}`,
        link: `./404`,
        path: `./nf`
      })
    }
  }

  useEffect(() => {
    menu()
  },[post])
  
  const Pagegen = (props: any) => {
    return <span onClick={Handlechange} className="menubtn" data-index={props.id-1}>{props.number}</span>
  }
  
  const Page = () => {
    const rows = new Array(15).fill(1)
  
    return (
      <section className={styles.sidebar}>
        {rows.map((el,i) => {
            return <Pagegen key={i} number={`0${i+1}`} id={i} />
        })}
      </section>
    )
}

  return (
    <>
      <main className={styles.container}>
        <Head>
          <meta name="description" content="#" />
          <meta name="keywords" content="#" />
          <meta name="author" content="Deep" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />  
          <title>NextBit</title>
          <meta name="Blog Template" content="Generated by create next app" />
          <link rel="icon" href="/nb.png" />
        </Head>
        <h1 className={styles.head}>{posts.heading}</h1>
      </main>
      
      <div className={styles.content}>

        <Page />

        <section className={styles.postBody}>
          <section className={styles.post}>
            <div>
              <Image src={post.image} alt={post.title} width={650} height={375} layout='intrinsic' />
            </div>
            <div>
              <span> {post.title} </span>
            </div>
          </section>
          
          <section className={styles.posttext}>
            <p>{post.content}</p>
            <Link href={post.path} as={post.link}>
              <span>
                Read More
                <Image src="/right-arrow.svg" alt="right-arrow" width={29} height={29} layout='intrinsic' />
              </span>
            </Link>
          </section>
        </section>

      </div>
      <footer></footer>
    </>
  )
}

export async function getServerSideProps( {params, req, res} ) {
  const response = await fetch(`${process.env.API_URL}/api/blog/`)
  if (!response.ok) {
    res.writeHead(302, {Location: '/nf'}).end()
    return {
      props : {}
    }
  }

  const data = await response.json()

  if (data) {
    return {
      props : {
        posts : data
      }
    }
  }
}

export default Home