import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../src/styles/Home.module.css'
import menu from '../src/scripts/menu.mjs'
import Link from 'next/link'

const legend = {
  "01": "one",
  "02": "two",
  "03": "three",
  "04": "four",
}

export default function Home(props: any) {

  const urlValidate = (url: any) => {
    
    let flag = 0
    Object.keys(props.title).map(key => {
      if (key == url) {
        console.log(`${key}: ${url}`)
        flag = 1
      }
    })
    if (flag == 1) return 1
    else return 0
  }

  const [post, Setpost] = React.useState({
    title: `${props.title.one}`,
    image: `${props.images.one}`,
    content: `${props.content.one}`,
    current: `one`,
    link: `./${props.title.one}`,
    path: `./[id]`
  })

  const Handlechange = (e: any) => {
    if (urlValidate(legend[e.target.innerHTML]) == 1) {
      Setpost({
        title: `${props.title[legend[e.target.innerHTML]]}`,
        image: `${props.images[legend[e.target.innerHTML]]}`,
        content: `${props.content[legend[e.target.innerHTML]]}`,
        current: `${legend[e.target.innerHTML]}`,
        link: `./${props.title[legend[e.target.innerHTML]]}`,
        path: `./[id]`
      })
    }
    else {
      Setpost({
        title: ``,
        image: ``,
        content: ``,
        current: `${legend[e.target.innerHTML]}`,
        link: `./${props.title[legend[e.target.innerHTML]]}`,
        path: `./[...params]`
      })
    }
    // console.log("rr")
  }

  useEffect(() => {
    menu()
  },[post])
  
  const Pagegen = (props: any) => {
    return <span onClick={Handlechange} className="menubtn" data-index={props.id-1}>{props.number}</span>
  }
  
  const Page = () => {
    var rows = []
    for (var i = 1; i <= 8; i++) {
      rows.push(<Pagegen key={i} number={`0${i}`} id={i} />)
    }
  
    return (
      <section className={styles.sidebar}>
        {rows}
      </section>
    )
  }

  return (
    <>
      <main className={styles.container}>
        <Head>
          <title>NextBit</title>
          <meta name="Blog Template" content="Generated by create next app" />
          <link rel="icon" href="/nb.png" />
        </Head>
        <h1 className={styles.head}>{props.heading}</h1>
      </main>
      
      <div className={styles.content}>

        <Page />

        <section className={styles.post}>
          <div>
            <Image src={post.image} alt={post.title} width={650} height={375} />
          </div>
          <div>
            <span> {post.title} </span>
          </div>
        </section>
        
        <section className={styles.posttext}>
          <span>{post.content}</span>
            <Link href={post.path} as={post.link}>
              <span>
                Read More
                <Image src="/right-arrow.svg" alt="right-arrow" width={29} height={29} />
              </span>
            </Link>
        </section>

      </div>
      <footer></footer>
    </>
  )
}
